#!/usr/bin/env python3

# TODO

import os
import sys

from analyzer import Analyzer
from termcolor import colored
from helpers import get_user_timeline

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @username")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    # store tweets from user in a list, "tweets"
    tweets = get_user_timeline(sys.argv[1])

    # assign scores to each of the tweets
    for tweet in tweets:
        # analyze word
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored("1 {}".format(tweet), "green"))
        elif score < 0.0:
            print(colored("-1 {}".format(tweet), "red"))
        else:
            print(colored("-1 {}".format(tweet), "yellow"))


if __name__ == "__main__":
    main()

